import {
  BlueIcons,
  NeutralIcons,
  WhiteIcons,
} from '../../../../shared/GlobalStyle'

export const SiteMenuList = [
  {
    id: 'Profile',
    name: 'Heather Johnson',
    src: BlueIcons.BlueProfile,
    whiteIcon: WhiteIcons.White_Account_16_2x,
    alt: 'Profile icon',
    category: 'profile',
    hasSubMenu: false,
    dropdownItem: [],
  },
  {
    id: 'Account',
    name: 'Account',
    src: NeutralIcons.Neutral_Account_16_2x,
    whiteIcon: WhiteIcons.White_Account_16_2x,
    alt: 'Account icon',
    category: 'default',
    hasSubMenu: true,
    isDropdownOpen: false,
    dropdownItem: [
      { routeTitle: 'Balance', openAtNewTab: false },
      { routeTitle: 'Holdings', openAtNewTab: false },
      { routeTitle: 'Activity', openAtNewTab: false },
      { routeTitle: 'Income', openAtNewTab: false },
      { routeTitle: 'CreditPlus', openAtNewTab: false },
      { routeTitle: 'Unrealized Gain/Loss', openAtNewTab: false },
      { routeTitle: 'Realized Gain/Loss', openAtNewTab: false },
    ],
  },
  {
    id: 'Documents',
    name: 'Documents',
    src: NeutralIcons.Neutral_Document_16_2x,
    whiteIcon: NeutralIcons.Neutral_Document_16_2x,
    alt: 'Document icon',
    category: 'default',
    hasSubMenu: true,
    isDropdownOpen: false,
    dropdownItem: [
      { routeTitle: 'Monthly Statements', openAtNewTab: false },
      { routeTitle: 'Trade Confirmations', openAtNewTab: false },
      { routeTitle: 'Tax Statements', openAtNewTab: false },
      { routeTitle: 'Open Order Confirmations', openAtNewTab: false },
      { routeTitle: 'Shareholder Confirmations', openAtNewTab: false },
      { routeTitle: 'CreditPlus Documents', openAtNewTab: false },
      { routeTitle: 'Performance Reports', openAtNewTab: false },
    ],
  },

  {
    id: 'Trade',
    name: 'Trade',
    src: NeutralIcons.Neutral_Quotes_16_2x,
    whiteIcon: NeutralIcons.Neutral_Quotes_16_2x,
    alt: 'Quotes&Charts icon',
    category: 'default',
    hasSubMenu: false,
    dropdownItem: [],
  },

  {
    id: 'Quotes',
    name: 'Quotes & Charts',
    src: NeutralIcons.Neutral_Quotes_16_2x,
    whiteIcon: NeutralIcons.Neutral_Quotes_16_2x,
    alt: 'Quotes&Charts icon',
    category: 'default',
    hasSubMenu: false,
    dropdownItem: [],
  },
  {
    id: 'Contact Us',
    name: 'Contact Us',
    src: NeutralIcons.Neutral_HelpCenter_16_2x,
    whiteIcon: NeutralIcons.Neutral_HelpCenter_16_2x,
    alt: 'Contact Us icon',
    category: 'default',
    hasSubMenu: false,
    dropdownItem: [],
  },
  {
    id: 'Sign Out',
    name: 'Sign Out',
    src: NeutralIcons.Neutral_Logout_16_2x,
    whiteIcon: NeutralIcons.Neutral_Logout_16_2x,
    alt: 'Signout out icon',
    category: 'action',
    hasSubMenu: false,
    dropdownItem: [],
  },
]
